"""add payable_to to bills

Revision ID: 3d2b3d288536
Revises: 8b6fd0549137
Create Date: 2026-06-04 22:50:34.030884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d2b3d288536'
down_revision: Union[str, None] = '8b6fd0549137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('payable_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bills', 'people', ['payable_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'payable_to')
    # ### end Alembic commands ###
