"""add emoji and color to person

Revision ID: 6172b9d62843
Revises: 65d49d59feb0
Create Date: 2026-06-04 21:42:31.351545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6172b9d62843'
down_revision: Union[str, None] = '65d49d59feb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('emoji', sa.String(), nullable=True))
    op.add_column('people', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'color')
    op.drop_column('people', 'emoji')
    # ### end Alembic commands ###
