"""add frequency and period to bills installments

Revision ID: 6943a5ea4c98
Revises: 992bf1a60e08
Create Date: 2026-06-04 22:15:01.115674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6943a5ea4c98'
down_revision: Union[str, None] = '992bf1a60e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_payments', sa.Column('period', sa.Integer(), nullable=True))
    op.alter_column('bill_payments', 'amount_paid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.add_column('bills', sa.Column('frequency', sa.String(), nullable=True))
    op.add_column('installment_payments', sa.Column('period', sa.Integer(), nullable=True))
    op.add_column('installments', sa.Column('frequency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installments', 'frequency')
    op.drop_column('installment_payments', 'period')
    op.drop_column('bills', 'frequency')
    op.alter_column('bill_payments', 'amount_paid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_column('bill_payments', 'period')
    # ### end Alembic commands ###
