"""change installment due_day to string

Revision ID: 8386fa89266d
Revises: 45500ef2d8f5
Create Date: 2026-06-04 22:32:48.948326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8386fa89266d'
down_revision: Union[str, None] = '45500ef2d8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('installments', 'due_day',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('installments', 'due_day',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
