"""add participant settlement tables

Revision ID: 924c39885705
Revises: 3d2b3d288536
Create Date: 2026-06-04 23:10:57.686465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '924c39885705'
down_revision: Union[str, None] = '3d2b3d288536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment_participant_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_participant_settlements_id'), 'installment_participant_settlements', ['id'], unique=False)
    op.create_table('bill_participant_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_participant_settlements_id'), 'bill_participant_settlements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_participant_settlements_id'), table_name='bill_participant_settlements')
    op.drop_table('bill_participant_settlements')
    op.drop_index(op.f('ix_installment_participant_settlements_id'), table_name='installment_participant_settlements')
    op.drop_table('installment_participant_settlements')
    # ### end Alembic commands ###
