"""make bill amount nullable

Revision ID: 992bf1a60e08
Revises: c9991d86ff36
Create Date: 2026-06-04 22:06:48.132069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '992bf1a60e08'
down_revision: Union[str, None] = 'c9991d86ff36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###
