"""add payment_method to expenses bills installments

Revision ID: a2153d07aac5
Revises: ac0e171384ea
Create Date: 2026-06-04 22:02:50.226375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a2153d07aac5'
down_revision: Union[str, None] = 'ac0e171384ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('installments', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installments', 'payment_method')
    op.drop_column('expenses', 'payment_method')
    op.drop_column('bills', 'payment_method')
    # ### end Alembic commands ###
