"""add due_day and participants to installments

Revision ID: ac0e171384ea
Revises: 6172b9d62843
Create Date: 2026-06-04 21:56:30.077402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac0e171384ea'
down_revision: Union[str, None] = '6172b9d62843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installments', sa.Column('due_day', sa.Integer(), nullable=True))
    op.add_column('installments', sa.Column('participants', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installments', 'participants')
    op.drop_column('installments', 'due_day')
    # ### end Alembic commands ###
