"""add participants and amounts to bills installments

Revision ID: c9991d86ff36
Revises: a2153d07aac5
Create Date: 2026-06-04 22:06:20.768438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c9991d86ff36'
down_revision: Union[str, None] = 'a2153d07aac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('participants', sa.JSON(), nullable=True))
    op.add_column('bills', sa.Column('participant_amounts', sa.JSON(), nullable=True))
    op.add_column('installments', sa.Column('participant_amounts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installments', 'participant_amounts')
    op.drop_column('bills', 'participant_amounts')
    op.drop_column('bills', 'participants')
    # ### end Alembic commands ###
